name: trackdemo2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  provider: ^6.1.2
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  maps_launcher: ^2.2.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  call_log: ^4.0.0
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  flutter_launcher_icons: "^0.13.1"
  firebase_storage: ^11.7.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
